[package]
name = "prometheus-nut-exporter"
version = "1.0.0-SNAPSHOT"
authors = ["HON95"]
license = "GPLv3"
description = "A Prometheus exporter for Network UPS Tools (NUT)."
keywords = ["prometheus", "openmetrics", "nut", "exporter"]
homepage = "https://github.com/HON95/prometheus-nut-exporter"
repository = "https://github.com/HON95/prometheus-nut-exporter"
edition = "2018"

[dependencies]
regex = "1.3.9"
bufstream = "0.1.4"
lazy_static = "1.4.0"
chrono = "0.4.11"
