name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: rustup component add clippy
    - name: Build
      run: cargo build --verbose
    - name: Run Clippy
      run: cargo clippy -- -D warnings
    - name: Check for trailing whitespace
      run: "! egrep -RHn '\\s+$' src/"
  publish-bleeding:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write version to file
      run: echo "0.0.0-SNAPSHOT+$(TZ=Etc/GMT date "+%Y-%m-%dT%H:%M:%SZ")" > VERSION
      shell: bash
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: hon95/prometheus-nut-exporter
        tags: bleeding
  publish-stable:
    if: github.event_name == 'release' && github.event.action == 'published' && startsWith(github.ref, 'refs/tags/v')
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Write version to file
      run: echo "${GITHUB_REF#refs/tags/v}" > VERSION
      shell: bash
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        repository: hon95/prometheus-nut-exporter
        tags: stable, ${{GITHUB_REF#refs/tags/v}}
